name: Screenoff
options:
  bundleIdPrefix: com.shimondeitel.screenofflog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Screenoff:
    type: application
    platform: iOS
    sources:
      - path: Screenoff
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.screenofflog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Screenoff/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  ScreenoffTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ScreenoffTests
      - path: Screenoff.storekit
    dependencies:
      - target: Screenoff
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.screenofflog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  ScreenoffUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ScreenoffUITests
    dependencies:
      - target: Screenoff
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.screenofflog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Screenoff:
    build:
      targets:
        Screenoff: all
        ScreenoffTests: [test]
        ScreenoffUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Screenoff.storekit
    test:
      config: Debug
      storeKitConfiguration: Screenoff.storekit
      targets:
        - ScreenoffTests
        - ScreenoffUITests
    archive:
      config: Release
